version: "3.8"
services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/models:/app/app/models
      - ./app/data:/app/app/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  wrapper:
    build:
      context: ./wrapper
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ASSISTANT_API_URL=http://assistant:5000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/assistant
    depends_on:
      - assistant
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assistant
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
